#! /bin/sh

xsetroot -cursor_name left_ptr
nitrogen --restore
picom --config /home/paul/.config/scripts/picom.conf &
dunst &

#og stuff
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/scripts/mouse-acc.sh &
lxsession &
#/home/paul/.config/scripts/timeshift.sh &


bspc monitor -d I II III IV V VI VII VIII IX X 

bspc config focused_border_color        "#6c71c4"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#902DF3"
#073642"
#bspc config pointer_follows_focus true
bspc config focus_follows_pointer true



#bspc config active_border_color "#902DF3"
bspc config border_width         2
bspc config window_gap           1

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a osu! desktop='^5'
bspc rule -a discord desktop='^4'
bspc rule -a Chromium desktop='^3'
bspc rule -a firefox desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
